site_name: ZJU 2023 CProgramming
site_url: https://note.tonycrane.cc/
repo_name: ZhouTimeMachine/CProgrammingBasics
repo_url: https://github.com/ZhouTimeMachine/CProgrammingBasics/
edit_uri: tree/master/docs
site_description: 浙江大学 2023 秋冬《程序设计与算法基础》课程网站
copyright: Copyright &copy; 2023-2024 <a href="https://github.com/ZhouTimeMachine" target="_blank" rel="noopener">ZhouTimeMachine</a>

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  icon:
    repo: fontawesome/brands/git-alt
    
plugins:
  - search

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

extra_css:
  - _css/style.css

nav:
  - Home: index.md